<a href="https://colab.research.google.com/github/simpsone4652/data_science/blob/main/Cwiczenia%2041-50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cwiczenie 41

In [2]:
import numpy as np
import pandas as pd


np.random.seed(42)
df = pd.DataFrame(data=np.random.randn(10), columns=['var1'])
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))
df['var1_sigmoid'] = df['var1'].apply(sigmoid)

df
# tutaj wpisz rozwiązanie

var1  var1_sigmoid
0  0.496714      0.621687
1 -0.138264      0.465489
2  0.647689      0.656489
3  1.523030      0.820984
4 -0.234153      0.441728
5 -0.234137      0.441732
6  1.579213      0.829093
7  0.767435      0.682966
8 -0.469474      0.384741
9  0.542560      0.632408

Cwiczenie 42

In [7]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(precision=4, suppress=True)
# tutaj wpisz rozwiązanie
df =pd.read_csv('data.csv')
scaler = StandardScaler()
scaler.fit(df)
df_scaled= scaler.transform(df)
df_scaled

array([[-0.4785, -0.2137, -0.4584, -0.5114,  0.0636],
       [ 1.3742,  0.3895,  1.2924,  1.4055, -0.616 ],
       [ 0.3777, -0.0178,  0.3905,  0.2783,  0.7424],
       [-0.4986, -0.4185, -0.4427, -0.5531,  0.4723],
       [-0.7449, -1.1397, -0.7236, -0.745 ,  0.0771],
       [ 1.8496,  2.1747,  1.9719,  1.8048,  1.3537],
       [ 2.2534,  0.5208,  2.2644,  2.4466,  0.5363],
       [ 0.9819, -1.0039,  0.9382,  0.8882, -0.0203],
       [-0.2294, -0.8236, -0.236 , -0.3987,  0.6429],
       [-0.069 , -0.6544, -0.1338, -0.1639, -2.1663],
       [-0.2666,  1.2665, -0.3344, -0.3457, -0.7709],
       [ 0.7557, -0.1692,  0.7035,  0.6847, -0.7183],
       [ 0.2374,  0.0445,  0.1351,  0.1047, -1.0339],
       [ 0.6068,  0.5164,  0.6293,  0.5087,  1.2613],
       [-0.5158, -1.6227, -0.5469, -0.551 , -0.6202],
       [ 1.4201,  1.498 ,  1.5189,  1.4114,  1.6167],
       [ 0.1916, -1.0818,  0.1005,  0.0766, -0.9977],
       [-1.14  ,  0.0066, -1.1321, -1.0148,  0.1098],
       [-2.0504, -1.3645, -1

Cwiczenie 43

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(precision=4, suppress=True)
# wpisz tutaj rozwiązanie
X_train=pd.read_csv('X_train.csv')
X_test= pd.read_csv('X_test.csv')
scaler = StandardScaler()
scaler.fit(X_train)
df_scaled= scaler.transform(X_train)
X_test = scaler.transform(X_test)
df_scaled

array([[-0.3491, -1.4385, -0.4117, -0.3905, -1.8637],
       [-0.2047,  0.3126, -0.1337, -0.2759,  1.0781],
       [-0.3293, -0.2151, -0.3174, -0.3644, -1.5799],
       ...,
       [ 0.0474, -0.5629, -0.0653, -0.0627, -2.2406],
       [-0.0404,  0.0997, -0.0315, -0.1557,  0.7484],
       [-0.5502,  0.3126, -0.6041, -0.5511, -1.1055]])

Cwiczenie 44

In [13]:
import numpy as np
import pandas as pd


def entropy(x):
    return np.round(-np.sum(x * np.log2(x)), 4)


df = pd.DataFrame({'val_1': np.arange(0.01, 1.0, 0.1), 'val_2': 1 - np.arange(0.01, 1.0, 0.1)})
# wpisz tutaj rozwiązanie
def entropy1(labels, base=None):
  value,counts = np.unique(labels, return_counts=True)
  return entropy(counts, base=base)

df['val_3']=

val_1  val_2
0   0.01   0.99
1   0.11   0.89
2   0.21   0.79
3   0.31   0.69
4   0.41   0.59
5   0.51   0.49
6   0.61   0.39
7   0.71   0.29
8   0.81   0.19
9   0.91   0.09

Cwiczenie 45

In [19]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score


# tutaj wpisz rozwiązanie
df = pd.read_csv('pred.csv')
acc = accuracy_score(df['y_true'], df['y_pred'])
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.7241


Cwiczenie 46

In [20]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix


# wpisz tutaj rozwiązanie
df = pd.read_csv('pred.csv')
confusion_matrix(df['y_true'], df['y_pred'])

array([[ 6,  1,  0],
       [ 3, 10,  2],
       [ 0,  2,  5]])

Cwiczenie 47

In [24]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

# tutaj wpisz rozwiązanie
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train,y_train)
acc =clf.score(X_test,y_test)
print(f'Acurcy: {acc:.4f}')

Acurcy: 0.9040


Cwiczenie 48

In [25]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

# wpisz tutaj rozwiązanie
clf = DecisionTreeClassifier(max_depth=6)
clf.fit(X_train,y_train)
acc =clf.score(X_test,y_test)
print(f'Acurcy: {acc:.4f}')

Acurcy: 0.9280


Cwiczenie 49

In [26]:
# wpisz tutaj rozwiązanie
clf = DecisionTreeClassifier(max_depth=6,min_samples_leaf=6)
clf.fit(X_train,y_train)
acc =clf.score(X_test,y_test)
print(f'Acurcy: {acc:.4f}')

Acurcy: 0.9300


Cwiczenie 50

In [28]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

# wpisz tutaj rozwiązanie
clf = DecisionTreeClassifier()
params = {'max_depth': np.arange(1, 10),
         'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20]}
grid_search = GridSearchCV(clf, param_grid=params, scoring='accuracy', cv=5)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)


{'max_depth': 6, 'min_samples_leaf': 6}
